### ISSUE TITLE
slick-examples 2.0.0-M3 do not compile on Dec 5, 2013

### ISSUE THREAD

**Issue by yaadyaad** [slick/slick-examples#24]
git clone ...
sbt update
sbt run

[info] Compiling 7 Scala sources to C:\Dev\projects\slick-examples\target\scala-2.10\classes...
[error] C:\Dev\projects\slick-examples\src\main\scala\com\typesafe\slick\examples\lifted\MultiDBCakeExample.sc
ala:26: reassignment to val
[error] Error occurred in an application involving default arguments.
[error]   private val picturesAutoInc = pictures returning pictures.map(_.id) into { case (p, id) => p.copy(id
 = id) }
[error]
 ^
[error] C:\Dev\projects\slick-examples\src\main\scala\com\typesafe\slick\examples\lifted\MultiDBCakeExample.sc
ala:27: type mismatch;
[error]  found   : com.typesafe.slick.examples.lifted.Picture
[error]  required: (String, Option[Int])
[error]   def insert(picture: Picture)(implicit session: Session): Picture = picturesAutoInc.insert(picture)
[error]                                                                                             ^
[error] two errors found
[error](compile:compile) Compilation failed
[error] Total time: 8 s, completed 05.12.2013 16:26:58

**Comment by szeiger** [comment]
Fixed and 2.0.0-M3 tag moved.
