### ISSUE TITLE
Package should be changed

### ISSUE THREAD

**Issue by mslinn** [slick/slick-examples#9]
The package for the code in this project is `scala.slick.examples`. I suggest that it be changed to a package that does not start with `scala`, such as `slick.examples`. My fork has this change, and also drops pre-existing tables in ForExample.scala

**Comment by szeiger** [comment]
We are planning to convert this project to a giter8 template. This will allow you to specify your own package name.

**Comment by mslinn** [comment]
My comment was intended to point out that the scala package is special, and should not be used by applications or example programs.
